blog/urls.py
from . import views
from django.urls import path
from django.contrib.auth.models import User

urlpatterns = [
    path("", views.PostList.as_view(), name='home'),
    path('<slug:slug>/', views.post_detail, name='post_detail'),
    path('post/new/', views.post_create, name='post_create'),
    path('post/drafts/<str:author>', views.PostDrafts.as_view(), name='drafts'),    
    path('post/edit/<slug:slug>', views.post_edit, name='post_edit'),
    path('post/delete/<slug:slug>', views.post_delete, name='post_delete'),
    path('add_address', views.add_address, name='add_address'),
    path('<slug:slug>/edit_comment/<int:comment_id>', 
         views.comment_edit, name='comment_edit'),
    path('<slug:slug>/delete_comment/<int:comment_id>',
         views.comment_delete, name='comment_delete'),
]

service_support_project/urls.py
from django.contrib import admin
from django.urls import path, include
from about import views as about_views

urlpatterns = [
    path('about/', include("about.urls"), name="about-urls"),
    path("accounts/", include("allauth.urls")),
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path("", include("blog.urls"), name="blog-urls"),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField

STATUS = ((0, "Draft"), (1, "Published"), 
          (2, "NotRectified"), (3,  "Rectified"), (99,  "RequestToDelete"))


# Create your models here.
class AddressField(models.Model):
    street = models.CharField(max_length=255, blank=True, null=True)
    city = models.CharField(max_length=100, blank=True, null=True)
    state = models.CharField(max_length=100, blank=True, null=True)
    postal_code = models.CharField(max_length=20, blank=True, null=True)
    country = models.CharField(max_length=100, blank=True, null=True)

    def __str__(self):
        return f"{self.street}, {self.city}, {self.state}, {self.country}"


class Post(models.Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="blog_posts")
    featured_image = CloudinaryField('image', default='placeholder')
    customer = models.CharField(max_length=100)
    customer_address = models.ForeignKey(AddressField, on_delete=models.CASCADE, related_name='+', blank=True, null=True)
    problem_reported = models.TextField()
    rectification = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)
    excerpt = models.TextField(blank=True)
    updated_on = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-created_on"]
                    
    def __str__(self):
        return f"{self.title} | written by {self.author}"


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="commenter")
    body = models.TextField(default="Thanks!")
    approved = models.TextField(default=False)
    created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-created_on"]
                    
    def __str__(self):
        return f"Comment {self.body} by {self.author}"
    

blog/forms.py
from .models import Comment, Post, AddressField
from django import forms
from django_summernote.widgets import SummernoteWidget


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'featured_image', 
                  'customer', 'customer_address', 'problem_reported', 
                  'rectification', 'status', 'excerpt']
        exclude = ['slug', ]
        widgets = {'problem_reported': SummernoteWidget(),  
                   'rectification': SummernoteWidget()}


class AddressForm(forms.ModelForm):
    class Meta:
        model = AddressField
        fields = ['street', 'city', 'state', 'postal_code', 'country']

    def clean(self):
        cleaned_data = super().clean()
        if AddressField.objects.filter(
            street=cleaned_data.get("street"),
            city=cleaned_data.get("city"),
            state=cleaned_data.get("state"),
            postal_code=cleaned_data.get("postal_code"),
            country=cleaned_data.get("country")
        ).exists():
            raise forms.ValidationError("This address already exists!")
        return cleaned_data

blog/views.py
from django.shortcuts import render, get_object_or_404, reverse
from django.views import generic
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.utils.text import slugify
from django.contrib.auth.models import User
from .models import Post, Comment, AddressField
from .forms import CommentForm, PostForm, AddressForm


class PostDrafts(generic.ListView):
    queryset = Post.objects.all().filter(status=0)
    template_name = "blog/index.html"
    paginate_by = 6

    def get_queryset(self):
        author = self.kwargs.get('author')
        if author:
            user = get_object_or_404(User, username=author)
            return Post.objects.filter(author=user, status=0)
        return Post.objects.all().filter(status=0)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        author = self.kwargs.get('author')
        if author:
            context['author'] = author
        return context


# Create your views here.
class PostList(generic.ListView):
    queryset = Post.objects.all().exclude(status=0).exclude(status=99)
    template_name = "blog/index.html"
    paginate_by = 6

    def get_queryset(self):
        queryset = super().get_queryset()
        query = self.request.GET.get("q")
        author_id = self.request.GET.get("user")

        if query:
            queryset = queryset.filter(title__icontains=query)
        if author_id:
            queryset = queryset.filter(author_id=author_id)

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["query"] = self.request.GET.get("q", "")
        context["selected_user"] = self.request.GET.get("user", "")
        context["users"] = User.objects.all()
        return context


def post_detail(request, slug):
    """
    Display an individual :model:'blog.Post'.

    **Context**

    ''post''
        An instance of :model:'blog.Post'.

    **Template:**

    :template:'blog/post_detail.html'
    """
    queryset = Post.objects.all()
    post = get_object_or_404(queryset, slug=slug)
    comments_all = post.comments.all().order_by("-created_on")
    comments = comments_all.filter(approved=True)
    comment_count = post.comments.filter(approved=True).count()
    if request.method == "POST":
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.author = request.user
            comment.post = post
            comment.save()
            messages.add_message(
                request, messages.SUCCESS,
                'Comment submitted and awaiting approval'
                )
    comment_form = CommentForm()
    return render(request, "blog/post_detail.html", 
                  {
                    "post": post,
                    "comments": comments,
                    "comment_count": comment_count,
                    "comment_form": comment_form,
                    },
                  )


def add_address(request):
    """
    add new customer address
    """
    if request.method == "POST":
        address_form = AddressForm(data=request.POST)
        if address_form.is_valid() and any(address_form.cleaned_data.values()):
            existing_address = AddressField.objects.filter(
                street=address_form.cleaned_data.get("street"), 
                city=address_form.cleaned_data.get("city"), 
                state=address_form.cleaned_data.get("state"), 
                postal_code=address_form.cleaned_data.get("postal_code"), 
                country=address_form.cleaned_data.get("country")
                ).first()

            if not existing_address:
                address_form.save()
                return HttpResponseRedirect(reverse('post_create'))  
    else:
        address_form = AddressForm()

    return render(
        request,
        "blog/add_address.html",
        {
            "address_form": address_form,
        },
    )


def post_create(request):
    """
    create new post
    """
    if request.method == "POST":
        post_form = PostForm(data=request.POST or None)
        address_form = AddressForm(data=request.POST or None)
        
        if address_form.is_valid():
            new_address = address_form.save()
            address_form = AddressForm()

        if post_form.is_valid():
            post = post_form.save(commit=False)
            slug = slugify(post.title)
            post.slug = slug
            post.author = request.user
            if new_address:
                post.customer_address = new_address
            post.save()
            address_form = AddressForm()
            messages.add_message(request, 
                                 messages.SUCCESS, "Post Created.")
            return HttpResponseRedirect(reverse('post_detail', args=[slug]))

    else:
        post_form = PostForm()
        address_form = AddressForm()

    return render(
        request,
        "blog/post_create.html",
        {
            "post_form": post_form,
            "address_form": address_form,
            "is_create": True
        },
    )


def post_edit(request, slug):
    """
    edit post
    """
    queryset = Post.objects.all()
    editpost = get_object_or_404(queryset, slug=slug)
    
    if request.method == "POST":
        editpost.delete()
        post_form = PostForm(data=request.POST)
        if post_form.is_valid():
            post = post_form.save(commit=False)
            slug = slugify(post.title)
            post.slug = slug
            post.author = request.user
            post.save()
            return HttpResponseRedirect(reverse('post_detail', args=[slug]))
    else:
        post_form = PostForm(instance=editpost)
        if post_form.is_valid():
            post = post_form.save(commit=False)
            slug = slugify(post.title)
            post.slug = slug
            post.author = request.user
            post.save()
            return HttpResponseRedirect(reverse('post_detail', args=[slug]))
        
    return render(
        request,
        "blog/post_create.html",
        {
            "post_form": post_form,
            "is_create": False
        },
    )


def post_delete(request, slug):
    """
    delete Post
    """
    queryset = Post.objects.all()
    post = get_object_or_404(queryset, slug=slug)

    if post.author == request.user:
        post.status = 99
        post.save()
        messages.add_message(request, messages.SUCCESS, 
                             'Admin Informed for deletion, if the reason is valid, it shall be processed!')
    else:
        messages.add_message(request, messages.ERROR, 
                             'You can only request to delete your own Posts!')

    return HttpResponseRedirect(reverse('post_detail', args=[slug]))


def comment_edit(request, slug, comment_id):
    """
    view to edit comments
    """
    if request.method == "POST":

        queryset = Post.objects.filter(status=1)
        post = get_object_or_404(queryset, slug=slug)
        comment = get_object_or_404(Comment, pk=comment_id)
        comment_form = CommentForm(data=request.POST, instance=comment)

        if comment_form.is_valid() and comment.author == request.user:
            comment = comment_form.save(commit=False)
            comment.post = post
            comment.approved = False
            comment.save()
            messages.add_message(request, messages.SUCCESS, 'Comment Updated!')
        else:
            messages.add_message(request, messages.ERROR, 'Error updating comment!')

    return HttpResponseRedirect(reverse('post_detail', args=[slug]))


def comment_delete(request, slug, comment_id):
    """
    view to delete comment
    """
    queryset = Post.objects.filter(status=1)
    post = get_object_or_404(queryset, slug=slug)
    comment = get_object_or_404(Comment, pk=comment_id)

    if comment.author == request.user:
        comment.delete()
        messages.add_message(request, messages.SUCCESS, 'Comment deleted!')
    else:
        messages.add_message(request, messages.ERROR, 
                             'You can only delete your own comments!')

    return HttpResponseRedirect(reverse('post_detail', args=[slug]))

blog/templates/blog/add_address.html
<!-- {% extends 'base.html' %}  -->
{% block content %}
{% load static %}
{% load crispy_forms_tags %}

<div class="container">
    <div class="row">
        <div class="col card mb-4  mt-3 left  top ">
            <div class="card-body " id="create_new_post" user="{{ user }}">
                <form id="addressForm" method="post"
          style="margin-top: 1.3em;" >
          {% csrf_token %}
            <h5>New Address</h5>
                {{ address_form | crispy }}
{% if user.is_authenticated %}
          <button id="submitButton" type="submit" name="action" value="saveAddress"
            class="btn btn-success mt-3" >Save</button>
          <button id="cancelButton" type="submit" name="action" value="cancel"
            class="btn btn-success mt-3" >Cancel</button>
{% endif %}
        </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

blog/templates/blog/index.html
{% extends "base.html" %}
{% load static %}


{% block content %}
<!-- index.html content starts here -->
<div class="card mb-4">
    <div class="card-header">
        <nav class="navbar navbar-expand-sm bg-light navbar-light ">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'home' %}">Posts</a>
                <div class="d-flex justify-content-between align-items-end gap-2">
                    {% if user.is_authenticated %}
                        <ul class="navbar-nav gap-2">
                            <li class="nav-item">
                                <a role="button" href="{% url 'post_create' %}" 
                                id="create_new_post" 
                                class="btn btn-primary nav-link text-white">New Post</a>
                            </li>
                            <li class="nav-item ">
                                <a role="button" href="{% url 'drafts' user.username %}" 
                                id="view_drafts" 
                                class="btn btn-secondary nav-link text-white">My Drafts</a>
                            </li>
                        </ul>
                    {% endif %}
                    {% if users %}
                        <form method="get" class="navbar-nav  gap-2">
                            <input type="text" name="q" value="{{ query }}" class="form-control me-2 "
                                placeholder="Search Posts...">
                            <div class="dropdown">
                                <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1"
                                    data-bs-toggle="dropdown" aria-expanded="false">
                                    Filter Posts By
                                </button>
                                <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                                    <li>
                                        <select name="user" class="form-select">
                                            <option value="">All Users</option>
                                            {% for u in users%}
                                                <option value="{{ u.id }}" 
                                                {% if selected_user == u.id|stringformat:"s" %}selected{% endif %}>
                                                {{ u.username }}
                                                </option>
                                            {% endfor %}
                                        </select>
                                    </li>
                                </ul>
                            </div>
                            <button type="submit" class="btn btn-warning ">Filter</button>
                        </form>
                    {% endif %}
                </div>
            </div>
        </nav>
    </div>
    <div class="card-body">
        <div class="container-fluid">
            <div class="row">

                <!-- Blog Entries Column -->
                <div class="col-12 mt-3 left ">
                    <div class="row">
                        {% for post in post_list %}
                        <div class="col-md-4 d-flex flex-wrap">
                            <div class="card mb-4 shadow-lg flex-fill">
                                <div class="card-body">
                                    <div class="image-container">
                                        {% if "placeholder" in post.featured_image.url %}
                                        <img class="card-img-top" src="{% static 'images/default.jpg' %}"
                                            alt="placeholder image">
                                        {% else %}
                                        <img class="card-img-top" src=" {{ post.featured_image.url }}"
                                            alt="{{ post.title }}">
                                        {% endif %}
                                        <div class="image-flash">
                                            <p class="author">Author: {{ post.author }}</p>
                                        </div>
                                    </div>
                                    <a href="{% url 'post_detail' post.slug %}" class="post-link">
                                        <h2 class="card-title">{{ post.title }}</h2>
                                        <p class="card-text">{{ post.excerpt }}</p>
                                    </a>

                                    <hr >
                                    <p class="card-text text-muted h6">{{ post.created_on}}
                                    </p>
                                </div>
                            </div>
                        </div>
                        {% if forloop.counter|divisibleby:3 %}
                    </div>
                    <div class="row">
                        {% endif %}
                        {% endfor %}

                    </div>
                </div>
            </div>
            {% if is_paginated %}
            <nav aria-label="Page navigation">
                <ul class="pagination justify-content-center gap-3">
                    {% if page_obj.has_previous %}
                    <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREV</a></li>
                    {% endif %}
                    {% if page_obj.has_next %}
                    <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT &raquo;</a></li>
                    {% endif %}
                </ul>
            </nav>
            {% endif %}
        </div>

    </div>
</div>
<!-- index.html content ends here -->
{% endblock %}

{% block copyright %}
Copyright 2025 Naveen Kumar Aremanda
{% endblock %}

blog/templates/blog/post_create.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
{% load crispy_forms_tags %}

<div class="container">
    <div class="row">
        <div class="col card mb-4  mt-3 left  top ">
            <div class="card-body " id="create_new_post" data-user="{{ user }}">
                <form id="postForm" method="post" style="margin-top: 1.3em;">
                    {% csrf_token %}
                    {{ post_form.title | as_crispy_field }}
                    {{ post_form.featured_image | as_crispy_field }}
                    {{ post_form.customer | as_crispy_field }}
                    {{ post_form.customer_address | as_crispy_field }}
                    {% if is_create %}
                    <button type="button" class="btn btn-outline-primary btn-sm mb-4"
                        onclick="document.getElementById('new-address').style.display=(document.getElementById('new-address').style.display === 'none') ? 'block' : 'none' ">
                        Add New Address
                    </button>

                    <div id="new-address" class="mb-4" style="display: none;">
                        <h5>New Address</h5>
                        {{ address_form | crispy }}
                    </div>

                    {% endif %}
                    {{ post_form.problem_reported | as_crispy_field }}
                    {{ post_form.rectification | as_crispy_field }}
                    {{ post_form.status | as_crispy_field }}
                    {{ post_form.excerpt | as_crispy_field }}
                    {% if user.is_authenticated %}
                    <button id="submitButton" type="submit" name="action" value="savePost"
                        class="btn btn-success mt-3">Save</button>
                    {% endif %}
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

blog/templates/blog/post_detail.html
{% extends 'base.html' %} 
{% block content %}
{% load static %}
{% load crispy_forms_tags %}

<div class="masthead  ">
    <div class="container">
        <div class="row g-0">
          {% if user.is_authenticated and post.author == user %}
          <div class="d-flex mb-1 justify-content-end gap-2">
            <a href="{% url 'post_edit' post.slug %}"
            id="edit_post" class="btn btn-sm btn-info ">Edit</a>
            <a href="{% url 'post_delete' post.slug %}"
            id="delete_post" class="btn btn-sm btn-danger text-white">Delete</a>
          </div>
          {% endif %}
            <div class="col-md-6 masthead-text">
                <!-- Post title goes in these h1 tags -->
                <h1 class="post-title">{{ post.title }}</h1>
                <!-- Post author goes before the | the post's created date goes after -->
                <p class="post-subtitle">{{ post.author }} | {{ post.created_on }}</p>
            </div>
            <div class="d-none d-md-block col-md-6 masthead-image">
                {% if "placeholder" in post.featured_image.url %}
                <img src="{% static 'images/default.jpg' %}" class="scale" alt="placeholder">
                {% else %}
                <img src="{{ post.featured_image.url }}" class="scale" alt="{{ post.title }}">
                {% endif %}
            </div>
        </div>
    </div>
</div>

<div class="container  ">
      <div class=" card mb-4 " >       
          
        <div class="card-header  d-flex justify-content-between align-items-center">
          <div>
            <ul class="nav nav-tabs card-header-tabs" role="tablist">
            <li class="nav-item">
              <a class="nav-link active" 
								data-bs-toggle="tab"
								href="#tab1" role="tab"
								aria-controls="tab1" aria-selected="true">Problem Reported</a>
            </li>
            <li class="nav-item">
              <a class="nav-link " 
								data-bs-toggle="tab"
								href="#tab2" role="tab"
								aria-controls="tab2" aria-selected="false">Rectification</a>
            </li>
            <li class="nav-item">
              <a class="nav-link " 
								data-bs-toggle="tab"
								href="#tab3" role="tab"
								aria-controls="tab3" aria-selected="false">Customer-Details</a>
            </li>
          </ul>
          </div>
          <div class="d-flex justify-content-end">
            {% if post.status == 0 %}
            <a role="button" class="btn btn-sm btn-warning" aria-disabled="true">{{ post.get_status_display }}</a>
            {% endif %}
            {% if post.status == 1 %}
            <a role="button" class="btn btn-sm btn-info" aria-disabled="true">{{ post.get_status_display }}</a>
            {% endif %}
            {% if post.status == 2 %}
            <a role="button" class="btn btn-sm btn-secondary" aria-disabled="true">{{ post.get_status_display }}</a>
            {% endif %}
            {% if post.status == 3 %}
            <a role="button" class="btn btn-sm btn-success" aria-disabled="true">{{ post.get_status_display }}</a>
            {% endif %}
            {% if post.status == 99 %}
            <a role="button" class="btn btn-sm btn-danger" aria-disabled="true">{{ post.get_status_display }}</a>
            {% endif %}
          </div>
        </div>
        <div class="card-body tab-content border" id="postcontent">
          <div class="tab-pane fade in m-0 active show" id="tab1"
								 aria-labelledby="tab1">
          {{ post.problem_reported | safe }}
              </div>
              <div class="tab-pane fade " id="tab2"
								role="tabpanel" aria-labelledby="tab2">
          {{ post.rectification | safe }}
              </div>
              <div class="tab-pane fade " id="tab3"
								role="tabpanel" aria-labelledby="tab3">
                <div class="mb-2">
                  <label class="form-label"><strong>Customer</strong></label>
                  <input type="text" class="form-control" value="{{ post.customer }}" readonly>
                </div>
                
                <div class="mb-2">
                  <div class="mb-2">
                    <h6>Customer Address</h6>
                    <label class="form-label">Street</label>
                    <input type="text" class="form-control" 
                    value="{{ post.customer_address.street }}" readonly>
                  </div>
                  <div class="mb-2">
                    <label class="form-label">City</label>
                    <input type="text" class="form-control" 
                    value="{{ post.customer_address.city }}" readonly>
                  </div>
                  <div class="mb-2">
                    <label class="form-label">State</label>
                    <input type="text" class="form-control" 
                    value="{{ post.customer_address.state }}" readonly>
                  </div>
                  <div class="mb-2">
                    <label class="form-label">Postal Code</label>
                    <input type="text" class="form-control" 
                    value="{{ post.customer_address.postal_code }}" readonly>
                  </div>
                  <div class="mb-2">
                    <label class="form-label">Country</label>
                    <input type="text" class="form-control" 
                    value="{{ post.customer_address.country }}" readonly>
                  </div>
                </div>
              </div>
          </div>
    </div>
 <!-- Displaying count of comments -->
  <div class="row">
    <div class="col-12">
      <strong class="text-secondary">
        <i class="far fa-comments"></i> {{ comment_count }}
      </strong>
    </div>
    <div class="col-12">
      <hr>
    </div>
  </div>
  <!-- Displaying Comments -->
  <div class="row">
    <div class="col-md-8 card mb-4  mt-3 ">
      <h3>Comments:</h3>
      <div class="card-body">
        <!-- We want a for loop inside the empty control tags
          to iterate through each comment in comments -->
        {% for comment in comments %}
        <div class="p-2 comments
          {% if not comment.approved and comment.author == user %}
          faded{% elif not comment.approved %} d-none{% endif %}">
          <p class="font-weight-bold">
            {{ comment.author }}
            <span class="font-weight-normal">
              {{ comment.created_on }}
            </span> wrote:
          </p>
          <div id="comment{{ comment.id }}">
            {{ comment.body | linebreaks }}
          </div>
          {% if not comment.approved and comment.author == user %}
          <p class="approval">
            This comment is awaiting approval
          </p>
          {% endif %}
          {% if user.is_authenticated and comment.author == user %}
           <button class="btn btn-delete" comment_id="{{ comment.id }}">Delete</button>
          <button class="btn btn-edit" comment_id="{{ comment.id }}">Edit</button>
          {% endif %}
        </div>
        <!-- Our for loop ends here -->
        {% endfor %}
      </div>
    </div>
    <!-- Creating New Comments -->
    <div class="col-md-4 card mb-4 mt-3">
      <div class="card-body">
        {% if user.is_authenticated %}
        <h3>Leave a comment:</h3>
        <p>Posting as: {{ user.username }}</p>
        <form id="commentForm" method="post"
          style="margin-top: 1.3em;">
          {{ comment_form | crispy }}
          {% csrf_token %}
          <button id="submitButton" type="submit"
            class="btn btn-signup btn-lg">Submit</button>
        </form>
        {% else %}
        <p>Log in to leave a comment</p>
        {% endif %}
      </div>
    </div>
  </div>
</div>
<!-- Delete confirmation modal -->
<div class="modal fade" id="deleteModal" tabindex="-1"
  aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title"
          id="deleteModalLabel">Delete comment?</h5>
        <button type="button" class="btn-close"
          data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Are you sure you want to delete your comment?
        This action cannot be undone.
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary"
          data-bs-dismiss="modal">Close</button>
        <a id="deleteConfirm" href="#" class="btn
          btn-danger">Delete</a>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="deletePostModal" tabindex="-1"
  aria-labelledby="deletePostModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title"
          id="deletePostModalLabel">Delete Post?</h5>
        <button type="button" class="btn-close"
          data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Are you sure you want to delete your Post?
        This action cannot be undone.
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary"
          data-bs-dismiss="modal">Close</button>
        <a id="deletePostConfirm" href="#" class="btn
          btn-danger">Delete</a>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

{% block extras %}
<script src="{% static 'js/comments.js' %}"></script>
{% endblock %}